### ISSUE TITLE
bad usage of the live demo 

### ISSUE THREAD

**Issue by EngMoathOmar** [ServiceStackApps/Imgur#2]
Hello  There, 
First of All thanks a lot for the Awesome ServiceStack... its really very great .. 

i just want to report a small issue , its about this tool imgur.servicestack.net .. 
its seems like some "bad/evil guys" had used the demo tool to upload porno images .... 
and i just want to ask you please to delete them ... 

i am so embarrassed to report such an issue to such a great Community like you.

Thats it. thanks again for the Awesome ServiceStack ... keep going

**Comment by mythz** [comment]
Ahh crap that's so annoying, one of the perils of making live demos available that accept user generated content!

Thanks for the heads up, I just hit `/reset` route which calls the [Reset operation to rebuild the site from preset urls](https://github.com/ServiceStackApps/Imgur/blob/master/src/Imgur/Global.asax.cs#L178) which is something I've added for situations just like this!

Anyways looks like the site is already back to its original state, thx for reporting!
